const NEW_USER = 'NEW_USER';
const LOGGED_USER = 'LOGGED_USER';
const CLICKED_PAGE = 'CLICKED_PAGE';
const CREATE_DESTINY = 'CREATE_DESTINY';

export {
  NEW_USER,
  LOGGED_USER,
  CLICKED_PAGE,
  CREATE_DESTINY,
};
